use std::net::SocketAddr;

use tracing::info;
use tracing_appender::non_blocking::WorkerGuard;
use tracing_subscriber::Layer;
use tracing_subscriber::filter::LevelFilter;
use tracing_subscriber::fmt;
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;
use utoipa::OpenApi;
use utoipa::openapi::path::{PathItem, Paths};

/// Runtime logging guard that keeps the non-blocking file writer alive.
#[derive(Debug)]
pub struct LoggingGuard {
    /// Guard owned for the whole process lifetime so buffered log lines flush.
    _file_guard: WorkerGuard,
}

/// Public API entry displayed in startup logs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ApiEndpoint {
    /// HTTP method used by the endpoint.
    pub method: &'static str,
    /// HTTP path exposed by the endpoint.
    pub path: String,
}

/// Initializes console and daily rolling file logging.
///
/// # Arguments
///
/// * `settings` - Logging settings loaded from runtime configuration.
///
/// # Returns
///
/// Returns a guard that must be kept alive until process shutdown.
pub fn init(settings: &crate::config::LoggingSettings) -> LoggingGuard {
    let level = parse_level_filter(&settings.level);
    let file_appender = tracing_appender::rolling::daily(&settings.path, "zembra.log");
    let (file_writer, file_guard) = tracing_appender::non_blocking(file_appender);
    let console_layer = fmt::layer()
        .with_target(true)
        .with_thread_ids(false)
        .with_thread_names(false)
        .with_filter(level);
    let file_layer = fmt::layer()
        .with_writer(file_writer)
        .with_ansi(false)
        .with_target(true)
        .with_thread_ids(false)
        .with_thread_names(false)
        .with_filter(level);

    tracing_subscriber::registry()
        .with(console_layer)
        .with(file_layer)
        .init();

    LoggingGuard {
        _file_guard: file_guard,
    }
}

/// Logs the service startup summary after the listener has been bound.
///
/// # Arguments
///
/// * `addr` - Bound socket address.
/// * `database_path` - Configured SQLite database file path.
pub fn log_startup_summary(addr: SocketAddr, database_path: &str) {
    let base_url = format!("http://{addr}");

    info!(%base_url, database_path, "Zembra backend started");
    info!("database path: {database_path}");
    info!("base url: {base_url}");
    info!("supported API:");

    for endpoint in supported_api_endpoints() {
        info!("{} {}", endpoint.method, endpoint.path);
    }
}

/// Returns supported API endpoints for startup logs.
///
/// # Returns
///
/// Returns OpenAPI endpoints plus runtime documentation routes.
pub fn supported_api_endpoints() -> Vec<ApiEndpoint> {
    let openapi = crate::api_doc::ApiDoc::openapi();
    let mut endpoints = endpoints_from_paths(&openapi.paths);

    endpoints.push(ApiEndpoint {
        method: "GET",
        path: "/api-docs/openapi.json".to_string(),
    });
    endpoints.push(ApiEndpoint {
        method: "GET",
        path: "/swagger-ui".to_string(),
    });
    endpoints.sort_by(|left, right| {
        left.path
            .cmp(&right.path)
            .then_with(|| left.method.cmp(right.method))
    });

    endpoints
}

/// Extracts endpoint methods and paths from an OpenAPI Paths object.
///
/// # Arguments
///
/// * `paths` - OpenAPI paths generated by utoipa.
///
/// # Returns
///
/// Returns a sorted API endpoint list.
fn endpoints_from_paths(paths: &Paths) -> Vec<ApiEndpoint> {
    let mut endpoints = Vec::new();

    for (path, item) in paths.paths.iter() {
        push_path_item_endpoint(&mut endpoints, path, item);
    }

    endpoints
}

/// Pushes configured operations from one OpenAPI path item into a display list.
///
/// # Arguments
///
/// * `endpoints` - Mutable endpoint list to extend.
/// * `path` - OpenAPI path string.
/// * `item` - OpenAPI path item containing optional method operations.
fn push_path_item_endpoint(endpoints: &mut Vec<ApiEndpoint>, path: &str, item: &PathItem) {
    let methods = [
        ("GET", item.get.is_some()),
        ("PUT", item.put.is_some()),
        ("POST", item.post.is_some()),
        ("DELETE", item.delete.is_some()),
        ("OPTIONS", item.options.is_some()),
        ("HEAD", item.head.is_some()),
        ("PATCH", item.patch.is_some()),
        ("TRACE", item.trace.is_some()),
    ];

    for (method, is_supported) in methods {
        if is_supported {
            endpoints.push(ApiEndpoint {
                method,
                path: path.to_string(),
            });
        }
    }
}

/// Parses a configured level into a tracing filter.
///
/// # Arguments
///
/// * `level` - User supplied level string.
///
/// # Returns
///
/// Returns the parsed level, falling back to `INFO` for invalid values.
fn parse_level_filter(level: &str) -> LevelFilter {
    level.parse::<LevelFilter>().unwrap_or(LevelFilter::INFO)
}

#[cfg(test)]
mod tests {
    #[test]
    fn supported_api_endpoints_include_openapi_methods() {
        let endpoints = super::supported_api_endpoints();

        assert!(
            endpoints
                .iter()
                .any(|endpoint| { endpoint.method == "GET" && endpoint.path == "/notes" })
        );
        assert!(
            endpoints
                .iter()
                .any(|endpoint| { endpoint.method == "POST" && endpoint.path == "/notes/recent" })
        );
        assert!(endpoints.iter().any(|endpoint| {
            endpoint.method == "GET" && endpoint.path == "/api-docs/openapi.json"
        }));
        assert!(
            endpoints
                .iter()
                .any(|endpoint| { endpoint.method == "GET" && endpoint.path == "/swagger-ui" })
        );
    }
}
